spring:
  application:
    name: bookstore
  datasource:
    url: jdbc:postgresql://database-1.cpgcowkvucco.us-east-1.rds.amazonaws.com:5432/bookstore
    username: postgres
    password: password
  jpa:
    #    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

server:
  port: 5000

